# SPDX-FileCopyrightText: 2022 Google LLC
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "clock-board"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Google LLC"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv-rt = "0.11.0"
bittide-sys = { path = "../../../firmware-support/bittide-sys" }
bittide-hal = { path = "../../../firmware-support/bittide-hal" }
bittide-macros = { path = "../../../firmware-support/bittide-macros" }
ufmt = "0.2.0"

[build-dependencies]
memmap-generate = { path = "../../../firmware-support/memmap-generate" }

[package.metadata.riscv-extensions]
required = []
forbidden = []
