# SPDX-FileCopyrightText: 2022 Google LLC
#
# SPDX-License-Identifier: CC0-1.0

[workspace]
members = [
  "bittide-hal",
  "bittide-hal-c",
  "bittide-macros",
  "bittide-sys",
  "gdb-trace",
  "memmap-generate",
]

resolver = "2"
