# SPDX-FileCopyrightText: 2024 Google LLC
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "memmap-markdown"
version = "0.1.0"
edition = "2024"

[dependencies]
memmap-generate = { path = "../../firmware-support/memmap-generate" }
heck = "0.5.0"
