# SPDX-FileCopyrightText: 2025 Google LLC
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "clash-num"
version = "0.1.0"
edition = "2024"

[features]
ufmt = ["dep:ufmt"]

[dependencies]
const_panic = "0.2.15"
get-random-const = "2.1.0"
paste = "1.0.15"

[dependencies.subst_macros]
git = "https://github.com/QBayLogic/subst_macros.git"
rev = "1273588cd7b854b8b6294cf54c7e238f77778ac4"
features = ["macro_metavar_expr"]

[dependencies.ufmt]
version = "0.2.0"
optional = true

[dev-dependencies]
seq-macro = "0.3.6"

[dev-dependencies.rand]
version = "0.9.2"
features = ["unbiased"]
