# SPDX-FileCopyrightText: 2024 Google LLC
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "switch_demo_pe_test"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Google LLC"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bittide-sys = { path = "../../../firmware-support/bittide-sys" }
bittide-hal = { path = "../../../firmware-support/bittide-hal" }
riscv-rt = "0.11.0"
ufmt = "0.2.0"

[dependencies.log]
version = "0.4.21"
features = ["max_level_trace", "release_max_level_info"]

[build-dependencies]
memmap-generate = { path = "../../../firmware-support/memmap-generate" }

[package.metadata.riscv-extensions]
required = []
forbidden = []
