# SPDX-FileCopyrightText: 2025 Google LLC
#
# SPDX-License-Identifier: CC0-1.0

[package]
name = "c_timer_wb"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Google LLC"]

[lints]
workspace = true

[dependencies]
riscv-rt = "0.11.0"
bittide-sys = { path = "../../../firmware-support/bittide-sys" }
ufmt = "0.2.0"

[build-dependencies]
memmap-generate = { path = "../../../firmware-support/memmap-generate" }
bittide-hal-c = { path = "../../../firmware-support/bittide-hal-c" }
cc = "1.0"
